// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: packet/model.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SCALING struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scale float32 `protobuf:"fixed32,1,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *SCALING) Reset() {
	*x = SCALING{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCALING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCALING) ProtoMessage() {}

func (x *SCALING) ProtoReflect() protoreflect.Message {
	mi := &file_packet_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCALING.ProtoReflect.Descriptor instead.
func (*SCALING) Descriptor() ([]byte, []int) {
	return file_packet_model_proto_rawDescGZIP(), []int{0}
}

func (x *SCALING) GetScale() float32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

type STACK_STATUS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Count  int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *STACK_STATUS) Reset() {
	*x = STACK_STATUS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *STACK_STATUS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STACK_STATUS) ProtoMessage() {}

func (x *STACK_STATUS) ProtoReflect() protoreflect.Message {
	mi := &file_packet_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STACK_STATUS.ProtoReflect.Descriptor instead.
func (*STACK_STATUS) Descriptor() ([]byte, []int) {
	return file_packet_model_proto_rawDescGZIP(), []int{1}
}

func (x *STACK_STATUS) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *STACK_STATUS) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_packet_model_proto protoreflect.FileDescriptor

var file_packet_model_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x1f, 0x0a, 0x07,
	0x53, 0x43, 0x41, 0x4c, 0x49, 0x4e, 0x47, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x3c, 0x0a,
	0x0c, 0x53, 0x54, 0x41, 0x43, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2f,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packet_model_proto_rawDescOnce sync.Once
	file_packet_model_proto_rawDescData = file_packet_model_proto_rawDesc
)

func file_packet_model_proto_rawDescGZIP() []byte {
	file_packet_model_proto_rawDescOnce.Do(func() {
		file_packet_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_packet_model_proto_rawDescData)
	})
	return file_packet_model_proto_rawDescData
}

var file_packet_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_packet_model_proto_goTypes = []interface{}{
	(*SCALING)(nil),      // 0: packet.SCALING
	(*STACK_STATUS)(nil), // 1: packet.STACK_STATUS
}
var file_packet_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_model_proto_init() }
func file_packet_model_proto_init() {
	if File_packet_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packet_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCALING); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*STACK_STATUS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packet_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_model_proto_goTypes,
		DependencyIndexes: file_packet_model_proto_depIdxs,
		MessageInfos:      file_packet_model_proto_msgTypes,
	}.Build()
	File_packet_model_proto = out.File
	file_packet_model_proto_rawDesc = nil
	file_packet_model_proto_goTypes = nil
	file_packet_model_proto_depIdxs = nil
}
